insert into Subscription_type VALUES ('FREE');
insert into Subscription_type VALUES ('ONE_TIME');
insert into Subscription_type VALUES ('SUBSCRIPTION');

INSERT INTO Country Values (  'INDIA');
INSERT INTO Country Values ( 'US');

INSERT INTO TAXES VALUES ('GST rates in %' , 0 , 12);
INSERT INTO COUNTRY_TAX_MAPPING VALUES (1,1);

INSERT INTO Course VALUES ('1', 1200 ,'Core Java', 1);
INSERT INTO Course VALUES ('2' ,1500, 'Advanced Java' ,2);
INSERT INTO Course VALUES ('3', 1000 , 'HTML/CSS' , 3);

INSERT INTO COURSE_COUNTRY_MAPPING VALUES (1 , 1);
INSERT INTO COURSE_COUNTRY_MAPPING VALUES (2 , 1);
INSERT INTO COURSE_COUNTRY_MAPPING VALUES (3 , 1);
INSERT INTO COURSE_COUNTRY_MAPPING VALUES (3 , 2);
INSERT INTO SUBSCRIPTION_PRICE VALUES (3, 400);